name: android_alarm_manager_plus
description: Flutter plugin for accessing the Android AlarmManager service, and
  running Dart code in the background when alarms fire.
version: 0.4.7
homepage: https://github.com/fluttercommunity/android_alarm_manager_plus
documentation: https://github.com/fluttercommunity/android_alarm_manager_plus
maintainer: Miguel Beltran (@miquelbeltran)
authors:
  - Flutter Community <community@flutter.zone>
  - Miguel Beltran <m@beltran.work>

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.androidalarmmanager
        pluginClass: AndroidAlarmManagerPlugin

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.0.0"
